# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34c9af9e8536d5064f116c70ff10dc179e266b6a4672067504539bc1518eb3caf34de02f48505ff2ef6f75b3ce323437358865486ebc803919b17c12115c730e

test:
  secret_key_base: 63f2b2ae462f84329959f6511aeb52d15fa0687cf06dbf16a9fad2b497eec2c3c4353e14c5d4c20873256d5fac26f8ddaeb03d9a9d453f12af3ef04f1c4312fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
